Registration
laraSaidSayedAhmad/Conduit pull request #3
Opened 2021-12-12 10:21 UTC by laraSaidSayedAhmad

2021-12-12 10:26 UTC, laraSaidSayedAhmad commented
I am going to add hash the passwords

2021-12-12 10:26 UTC, laraSaidSayedAhmad commented
I am going to add hash the passwords

2021-12-14 11:38 UTC, Abdallatif requested changes

2021-12-14 11:38 UTC, Abdallatif commented on app/root.tsx
> +        <link rel="stylesheet" href="//demo.productionready.io/main.css"></link>
you should define the links in the main route `app/routes/index.tsx`
```
export const links: LinksFunction = () => {
  return [{ rel: "stylesheet", href: "//demo.productionready.io/main.css" }];
};

Then in the Document you should keep rendering the `meta` & `links`
```
        <Meta />
        <Links />
```

2021-12-14 11:38 UTC, Abdallatif commented on prisma/seed.ts
> +  // shout-out to https://icanhazdadjoke.com/
?

2021-12-14 11:38 UTC, Abdallatif commented on app/routes/register.tsx
> +  console.log(userInfo);
no console logs

2021-12-14 11:38 UTC, Abdallatif commented on app/root.tsx
> -import {
I don't agree with most of the changes in this file. I still think we need `links`, `App`, `ErrorBoundary` & `CatchBoundary`.

2021-12-14 15:38 UTC, Abdallatif approved these changes

2021-12-14 15:50 UTC, merged